# Generated by Django 3.0.3 on 2020-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlesList', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Logo',
            field=models.ImageField(blank=True, default='def.png', upload_to=''),
        ),
    ]
