# Generated by Django 3.0.3 on 2020-03-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlesList', '0004_articles_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
