# Generated by Django 3.0.3 on 2020-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlesList', '0006_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
